version: '3.8'

services:
  backend:
    build: ./services/backend
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dev
      - SECRET_KEY=0e591a629acd95f06498086f72141014043d800fdd4b5df435cf4b9c97c96ed6
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8081
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:8081
    ports:
      - 8080:8080

  db:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data: